### ISSUE TITLE
can not build 

### ISSUE THREAD

**Issue by kykomi** [kinako4122/warikanchan#5]
I try to build but failed.  
The reason is below: 
* error: ~/nn.mp3: No such file or directory
* error: ~/azukifontB120/azukiB.ttf: No such file or directory
* error: ~/girl@2x.png: No such file or directory
* error: ~/result.png: No such file or directory

This is not important issue for submission to Apple.

**Comment by kinako4122** [comment]
Thank you for trying to build my app!
I put these files in my project directory.

so I hope you can build now.

**Comment by kykomi** [comment]
Thanks !
I can build now.  
Closed.
