### ISSUE TITLE
Deployment Target value  is correct ?

### ISSUE THREAD

**Issue by kykomi** [kinako4122/warikanchan#6]
Deployment Target is set to `9.2`. 
It means that the only users who uses iOS 9.2 or later version can download your app.  

You'd better to decrease the value in order to let many users to download.

**Comment by kinako4122** [comment]
That's really good point! Thank you!
I changed Deployment Target to 8.2 from 9.2 since my iPhone had been 8.2 until recently. 
let them download~~~~!!!
